# Generated by Django 4.1.5 on 2023-01-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['provider_name'], 'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='name',
            new_name='provider_name',
        ),
    ]
