# Generated by Django 4.1.5 on 2023-01-10 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_zipcode'),
        ('provider', '0002_alter_provider_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
