# Generated by Django 4.1.5 on 2023-01-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_zipcode'),
        ('provider', '0003_alter_provider_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='address',
        ),
        migrations.AddField(
            model_name='provider',
            name='address',
            field=models.ManyToManyField(related_name='provider_address', to='address.address'),
        ),
    ]
