# Generated by Django 4.1.5 on 2023-01-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
