# Generated by Django 4.1.5 on 2023-01-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set(),
        ),
    ]
