# Generated by Django 4.1.5 on 2023-01-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_unique_together'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price.price'),
        ),
    ]
