# Generated by Django 4.1.5 on 2023-01-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_unique_together'),
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.ManyToManyField(to='price.price'),
        ),
    ]
